### ISSUE TITLE
 IATI data updated wrong- affecting a number of publishers

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/ckanext-iati#174]
A publisher (the World Bank)  just flagged that the metadata on the IATI Registry for their[ organisation file](https://iatiregistry.org/dataset/worldbank-org) does not correctly reflect the date in [their XML file](http://siteresources.worldbank.org/INTSOPE/Resources/5929468-1305310586289/IATI_ORG.xml) (see screenshots below).

![image](https://user-images.githubusercontent.com/24607542/39358762-2163cae0-4a0f-11e8-859f-38379f6f0b69.png)

![image](https://user-images.githubusercontent.com/24607542/39358852-8f379e70-4a0f-11e8-91c4-5a1d135a5f25.png)

Same issue was flagged by other publishers in the past and changes were deployed to fix it. See [Github issue](https://github.com/IATI/ckanext-iati/issues/125) for reference. 

@derwas [Zendesk ticket](https://iati.zendesk.com/agent/tickets/6597) related to the issue.

**Comment by derwas** [comment]
IATI Archiver updates meta data. I have recently updated it and the issue is now fixed.

**Comment by derwas** [comment]
The issue has been fixed!!!

**Comment by andylolz** [comment]
> The issue has been fixed!!!

These are frequently incorrect, so it looks like the issue is still present. Here are a few examples:
 * https://iatiregistry.org/dataset/pact-organization1116
 * https://iatiregistry.org/dataset/asi-org
 * https://iatiregistry.org/dataset/afd-zw (wrong by 2 years)
 * https://iatiregistry.org/dataset/dfid-gb

**Comment by amy-silcock** [comment]
Hi @derwas USAID have also got in contact about this on Friday. I will assign the ticket to you on zendesk. Please can you respond to them?

**Comment by andylolz** [comment]
Here’s a CSV of the instances where the last updated timestamp in the data doesn’t match the last updated timestamp on the registry:
https://gist.github.com/andylolz/f640bcba69ee8f4b90629afaede7b576

It looks the timestamps for USAID have been fixed in the registry (today, I think) so they don’t feature in the above list.

**Comment by amy-silcock** [comment]
Hi @derwas, this is currently an issue for the United Nation Population Fund. They're asking about why the data has not been updated.

**Comment by derwas** [comment]
@amy-silcock is this issue still open?

**Comment by amy-silcock** [comment]
Hi @derwas, does this relate to the IATI archiver? If yes then I thought a longer term solution was to be found when we come to do the work on getting the IATI archiver to update all the metadata correctly.

**Comment by PetyaKangalova** [comment]
Adding another example flagged by the Climate Investment Funds:

- https://iatiregistry.org/dataset/cif-am (registry metadata says 2016-05-13 13:45, raw data  `last-updated-datetime="2018-06-19T12:54:13)
`

_Note: I have also renamed the title of the Github to reflect correctly that the issue is for a number of publishers, not just the World Bank._

**Comment by amy-silcock** [comment]
This is now fixed as per work with the IATI archiver. @derwas please can you link to relevant code change or github work?

**Comment by jahnvidave** [comment]
@derwas Thank you Wassim for responding directly to the ticket (ticket #7569) and for fixing this.

**Comment by jahnvidave** [comment]
Hi @derwas, re-opening the issue as Inter-American Development Bank updated their data on 07/12/2018, but the Registry metadata still says 23/11/2018 from their previous update.

Please can you look into this? (See Zendesk ticket #7680 for more info)

**Comment by derwas** [comment]
@jahnvidave can you please share what data are you referring to? 
I do not have access to that Zendesk ticket.

**Comment by jahnvidave** [comment]
Apologies Wassim. I have now copied you in to the ticket, and there are several datasets for IADB: https://iatiregistry.org/publisher/iadb
