### ISSUE TITLE
Incorrect IATI standard version sometimes shown in dataset metadata

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#180]
Continued from #117.

At present, the following 213 datasets appear to have issues (copied from https://github.com/IATI/ckanext-iati/issues/117#issuecomment-385411900):

actual version (in data) | registry version (in metadata) | dataset URL | dataset name
----------------|------------------|-------------|-------------
2.01 |  | https://iatiregistry.org/dataset/gac-amc-act_2_3 | gac-amc-act_2_3
2.01 | n/a | https://iatiregistry.org/dataset/gac-amc-org | gac-amc-org
2.01 | None | https://iatiregistry.org/dataset/nri-gb | nri-gb
2.01 | None | https://iatiregistry.org/dataset/nri-org | nri-org
2.01 | None | https://iatiregistry.org/dataset/said-org | said-org
2.01 | None | https://iatiregistry.org/dataset/wfwiuk-activities | wfwiuk-activities
2.02 |  | https://iatiregistry.org/dataset/3ie-dpw | 3ie-dpw
2.02 |  | https://iatiregistry.org/dataset/esrf-activities | esrf-activities
2.02 |  | https://iatiregistry.org/dataset/uncdf-activities | uncdf-activities
2.02 | 2.01 | https://iatiregistry.org/dataset/plannlno-ao | plannlno-ao
2.02 | None | https://iatiregistry.org/dataset/aauk-activities | aauk-activities
2.02 | None | https://iatiregistry.org/dataset/ablechildafrica-activities | ablechildafrica-activities
2.02 | None | https://iatiregistry.org/dataset/abt-activities | abt-activities
2.02 | None | https://iatiregistry.org/dataset/acet-activities | acet-activities
2.02 | None | https://iatiregistry.org/dataset/achest-activities | achest-activities
2.02 | None | https://iatiregistry.org/dataset/acted-lb | acted-lb
2.02 | None | https://iatiregistry.org/dataset/aet-activities | aet-activities
2.02 | None | https://iatiregistry.org/dataset/afemena-activities | afemena-activities
2.02 | None | https://iatiregistry.org/dataset/afewinternational-activities | afewinternational-activities
2.02 | None | https://iatiregistry.org/dataset/afrikids-activities | afrikids-activities
2.02 | None | https://iatiregistry.org/dataset/agencia_do_zambeze-activities | agencia_do_zambeze-activities
2.02 | None | https://iatiregistry.org/dataset/amrefeth-et | amrefeth-et
2.02 | None | https://iatiregistry.org/dataset/amrefhq-activities | amrefhq-activities
2.02 | None | https://iatiregistry.org/dataset/amrefmw-activities | amrefmw-activities
2.02 | None | https://iatiregistry.org/dataset/amrefnl-activities | amrefnl-activities
2.02 | None | https://iatiregistry.org/dataset/apc-activities | apc-activities
2.02 | None | https://iatiregistry.org/dataset/arcfge-activities | arcfge-activities
2.02 | None | https://iatiregistry.org/dataset/asf-be | asf-be
2.02 | None | https://iatiregistry.org/dataset/asf-bi | asf-bi
2.02 | None | https://iatiregistry.org/dataset/asf-cd | asf-cd
2.02 | None | https://iatiregistry.org/dataset/asf-ug | asf-ug
2.02 | None | https://iatiregistry.org/dataset/atnf-activities | atnf-activities
2.02 | None | https://iatiregistry.org/dataset/atsf-activities | atsf-activities
2.02 | None | https://iatiregistry.org/dataset/awid-activities | awid-activities
2.02 | None | https://iatiregistry.org/dataset/bcm-cf-mw | bcm-cf-mw
2.02 | None | https://iatiregistry.org/dataset/beis-activities | beis-activities
2.02 | None | https://iatiregistry.org/dataset/bond-activities | bond-activities
2.02 | None | https://iatiregistry.org/dataset/bothends-298 | bothends-298
2.02 | None | https://iatiregistry.org/dataset/bothends-498 | bothends-498
2.02 | None | https://iatiregistry.org/dataset/bothends-798 | bothends-798
2.02 | None | https://iatiregistry.org/dataset/bothends-998 | bothends-998
2.02 | None | https://iatiregistry.org/dataset/bothends-nl | bothends-nl
2.02 | None | https://iatiregistry.org/dataset/bucksfarm-activities | bucksfarm-activities
2.02 | None | https://iatiregistry.org/dataset/c40cities-activities | c40cities-activities
2.02 | None | https://iatiregistry.org/dataset/cabi-998 | cabi-998
2.02 | None | https://iatiregistry.org/dataset/cal-ke | cal-ke
2.02 | None | https://iatiregistry.org/dataset/cal-mm | cal-mm
2.02 | None | https://iatiregistry.org/dataset/cal-np | cal-np
2.02 | None | https://iatiregistry.org/dataset/carenederland-activities | carenederland-activities
2.02 | None | https://iatiregistry.org/dataset/cdi-so | cdi-so
2.02 | None | https://iatiregistry.org/dataset/cfyas-activities | cfyas-activities
2.02 | None | https://iatiregistry.org/dataset/chai-activities | chai-activities
2.02 | None | https://iatiregistry.org/dataset/climate_centre-activities | climate_centre-activities
2.02 | None | https://iatiregistry.org/dataset/cncd-be | cncd-be
2.02 | None | https://iatiregistry.org/dataset/cncd-cd | cncd-cd
2.02 | None | https://iatiregistry.org/dataset/cocnl_publisher-activities | cocnl_publisher-activities
2.02 | None | https://iatiregistry.org/dataset/cordaid-activities | cordaid-activities
2.02 | None | https://iatiregistry.org/dataset/crane-activities | crane-activities
2.02 | None | https://iatiregistry.org/dataset/creausa-org-activities | creausa-org-activities
2.02 | None | https://iatiregistry.org/dataset/creausa-org-org | creausa-org-org
2.02 | None | https://iatiregistry.org/dataset/crehpa-activities | crehpa-activities
2.02 | None | https://iatiregistry.org/dataset/dai-activities | dai-activities
2.02 | None | https://iatiregistry.org/dataset/dcaf-mk | dcaf-mk
2.02 | None | https://iatiregistry.org/dataset/dcaf-tn | dcaf-tn
2.02 | None | https://iatiregistry.org/dataset/dciecpatnl-lr | dciecpatnl-lr
2.02 | None | https://iatiregistry.org/dataset/dec-uk-activities | dec-uk-activities
2.02 | None | https://iatiregistry.org/dataset/decp-id | decp-id
2.02 | None | https://iatiregistry.org/dataset/dggf_financing_local_smes-activities | dggf_financing_local_smes-activities
2.02 | None | https://iatiregistry.org/dataset/dhsc-activities | dhsc-activities
2.02 | None | https://iatiregistry.org/dataset/edt_kenya-ke | edt_kenya-ke
2.02 | None | https://iatiregistry.org/dataset/edt_kenya-org | edt_kenya-org
2.02 | None | https://iatiregistry.org/dataset/ehpea-activities | ehpea-activities
2.02 | None | https://iatiregistry.org/dataset/ehpea-org | ehpea-org
2.02 | None | https://iatiregistry.org/dataset/eif-activities | eif-activities
2.02 | None | https://iatiregistry.org/dataset/eip-ye | eip-ye
2.02 | None | https://iatiregistry.org/dataset/ejc-activities | ejc-activities
2.02 | None | https://iatiregistry.org/dataset/ejc-org | ejc-org
2.02 | None | https://iatiregistry.org/dataset/emms-in | emms-in
2.02 | None | https://iatiregistry.org/dataset/etmkdw-activities | etmkdw-activities
2.02 | None | https://iatiregistry.org/dataset/etmkdw-org | etmkdw-org
2.02 | None | https://iatiregistry.org/dataset/fact-activities | fact-activities
2.02 | None | https://iatiregistry.org/dataset/fian-belgium-org | fian-belgium-org
2.02 | None | https://iatiregistry.org/dataset/foei-998 | foei-998
2.02 | None | https://iatiregistry.org/dataset/foenl-activities | foenl-activities
2.02 | None | https://iatiregistry.org/dataset/free_press_unlimited-activities | free_press_unlimited-activities
2.02 | None | https://iatiregistry.org/dataset/freeagirl-bd | freeagirl-bd
2.02 | None | https://iatiregistry.org/dataset/freeagirl-in | freeagirl-in
2.02 | None | https://iatiregistry.org/dataset/freeagirl-nl | freeagirl-nl
2.02 | None | https://iatiregistry.org/dataset/freeagirl-th | freeagirl-th
2.02 | None | https://iatiregistry.org/dataset/fwf-tr | fwf-tr
2.02 | None | https://iatiregistry.org/dataset/gi-jhu-gh | gi-jhu-gh
2.02 | None | https://iatiregistry.org/dataset/giro555-activities | giro555-activities
2.02 | None | https://iatiregistry.org/dataset/goal-activities | goal-activities
2.02 | None | https://iatiregistry.org/dataset/gppac-activities | gppac-activities
2.02 | None | https://iatiregistry.org/dataset/halo-af | halo-af
2.02 | None | https://iatiregistry.org/dataset/halo-co | halo-co
2.02 | None | https://iatiregistry.org/dataset/halo-ps | halo-ps
2.02 | None | https://iatiregistry.org/dataset/halo-so | halo-so
2.02 | None | https://iatiregistry.org/dataset/halo-sy | halo-sy
2.02 | None | https://iatiregistry.org/dataset/halo-ua | halo-ua
2.02 | None | https://iatiregistry.org/dataset/halo-xk | halo-xk
2.02 | None | https://iatiregistry.org/dataset/handinhand-activities | handinhand-activities
2.02 | None | https://iatiregistry.org/dataset/healthnet-activities | healthnet-activities
2.02 | None | https://iatiregistry.org/dataset/healthpartners-international-ss | healthpartners-international-ss
2.02 | None | https://iatiregistry.org/dataset/hiil_mfa-activities | hiil_mfa-activities
2.02 | None | https://iatiregistry.org/dataset/hiuk-289 | hiuk-289
2.02 | None | https://iatiregistry.org/dataset/hiuk-bd | hiuk-bd
2.02 | None | https://iatiregistry.org/dataset/horizons-jo | horizons-jo
2.02 | None | https://iatiregistry.org/dataset/hpa-activities | hpa-activities
2.02 | None | https://iatiregistry.org/dataset/hsi-activities | hsi-activities
2.02 | None | https://iatiregistry.org/dataset/hsi-org | hsi-org
2.02 | None | https://iatiregistry.org/dataset/ibis_denmark-activities | ibis_denmark-activities
2.02 | None | https://iatiregistry.org/dataset/icf-mr | icf-mr
2.02 | None | https://iatiregistry.org/dataset/icf-ng | icf-ng
2.02 | None | https://iatiregistry.org/dataset/icf-np | icf-np
2.02 | None | https://iatiregistry.org/dataset/idlo-activities | idlo-activities
2.02 | None | https://iatiregistry.org/dataset/ids-activities | ids-activities
2.02 | None | https://iatiregistry.org/dataset/ieu-998 | ieu-998
2.02 | None | https://iatiregistry.org/dataset/ihaa-activities | ihaa-activities
2.02 | None | https://iatiregistry.org/dataset/imcw_admin-activities | imcw_admin-activities
2.02 | None | https://iatiregistry.org/dataset/inbar-ke | inbar-ke
2.02 | None | https://iatiregistry.org/dataset/ippf-activities | ippf-activities
2.02 | None | https://iatiregistry.org/dataset/irc_inc-activities | irc_inc-activities
2.02 | None | https://iatiregistry.org/dataset/irc_uk-activities | irc_uk-activities
2.02 | None | https://iatiregistry.org/dataset/irw-activities | irw-activities
2.02 | None | https://iatiregistry.org/dataset/itpc-998 | itpc-998
2.02 | None | https://iatiregistry.org/dataset/itpc-kg | itpc-kg
2.02 | None | https://iatiregistry.org/dataset/iwda-au | iwda-au
2.02 | None | https://iatiregistry.org/dataset/kipkelion-activities | kipkelion-activities
2.02 | None | https://iatiregistry.org/dataset/kit-activities | kit-activities
2.02 | None | https://iatiregistry.org/dataset/learningforlife-679 | learningforlife-679
2.02 | None | https://iatiregistry.org/dataset/lepra-activities | lepra-activities
2.02 | None | https://iatiregistry.org/dataset/lftw-be-cd | lftw-be-cd
2.02 | None | https://iatiregistry.org/dataset/lftw-be-rw | lftw-be-rw
2.02 | None | https://iatiregistry.org/dataset/lftw-be-tz | lftw-be-tz
2.02 | None | https://iatiregistry.org/dataset/lstm-gb | lstm-gb
2.02 | None | https://iatiregistry.org/dataset/mainline-298 | mainline-298
2.02 | None | https://iatiregistry.org/dataset/mainline-798 | mainline-798
2.02 | None | https://iatiregistry.org/dataset/mamac-activities | mamac-activities
2.02 | None | https://iatiregistry.org/dataset/mce-activities | mce-activities
2.02 | None | https://iatiregistry.org/dataset/mml-activities | mml-activities
2.02 | None | https://iatiregistry.org/dataset/msi-activities | msi-activities
2.02 | None | https://iatiregistry.org/dataset/mvo_nederland-activities | mvo_nederland-activities
2.02 | None | https://iatiregistry.org/dataset/nrc-298 | nrc-298
2.02 | None | https://iatiregistry.org/dataset/nrc-589 | nrc-589
2.02 | None | https://iatiregistry.org/dataset/nrc-679 | nrc-679
2.02 | None | https://iatiregistry.org/dataset/nrc-798 | nrc-798
2.02 | None | https://iatiregistry.org/dataset/nrc-998 | nrc-998
2.02 | None | https://iatiregistry.org/dataset/nrc-so | nrc-so
2.02 | None | https://iatiregistry.org/dataset/nrc-ye | nrc-ye
2.02 | None | https://iatiregistry.org/dataset/nri-998 | nri-998
2.02 | None | https://iatiregistry.org/dataset/nri-za | nri-za
2.02 | None | https://iatiregistry.org/dataset/oneacrefund-activities | oneacrefund-activities
2.02 | None | https://iatiregistry.org/dataset/orbis_ethiopia-et | orbis_ethiopia-et
2.02 | None | https://iatiregistry.org/dataset/orbis_ethiopia-org | orbis_ethiopia-org
2.02 | None | https://iatiregistry.org/dataset/orbis_international-et | orbis_international-et
2.02 | None | https://iatiregistry.org/dataset/orbis_international-org | orbis_international-org
2.02 | None | https://iatiregistry.org/dataset/orbis_uk-et | orbis_uk-et
2.02 | None | https://iatiregistry.org/dataset/orbis_uk-org | orbis_uk-org
2.02 | None | https://iatiregistry.org/dataset/orbis_uk-zm | orbis_uk-zm
2.02 | None | https://iatiregistry.org/dataset/orientame-co | orientame-co
2.02 | None | https://iatiregistry.org/dataset/orientame-org | orientame-org
2.02 | None | https://iatiregistry.org/dataset/oxfamus-activities | oxfamus-activities
2.02 | None | https://iatiregistry.org/dataset/palladium-activities | palladium-activities
2.02 | None | https://iatiregistry.org/dataset/plan_uk-activities | plan_uk-activities
2.02 | None | https://iatiregistry.org/dataset/prefa_1-ug | prefa_1-ug
2.02 | None | https://iatiregistry.org/dataset/psi-298 | psi-298
2.02 | None | https://iatiregistry.org/dataset/pstc_1102-activities | pstc_1102-activities
2.02 | None | https://iatiregistry.org/dataset/pumnl-activities | pumnl-activities
2.02 | None | https://iatiregistry.org/dataset/pwcplindia-org | pwcplindia-org
2.02 | None | https://iatiregistry.org/dataset/rc-activities | rc-activities
2.02 | None | https://iatiregistry.org/dataset/rutgers-activities | rutgers-activities
2.02 | None | https://iatiregistry.org/dataset/saferworld-activities | saferworld-activities
2.02 | None | https://iatiregistry.org/dataset/scnl-298 | scnl-298
2.02 | None | https://iatiregistry.org/dataset/scnl-589 | scnl-589
2.02 | None | https://iatiregistry.org/dataset/scnl-ng | scnl-ng
2.02 | None | https://iatiregistry.org/dataset/scnl-ss | scnl-ss
2.02 | None | https://iatiregistry.org/dataset/scnl-ye | scnl-ye
2.02 | None | https://iatiregistry.org/dataset/sense_international-ke | sense_international-ke
2.02 | None | https://iatiregistry.org/dataset/sfcg-activities | sfcg-activities
2.02 | None | https://iatiregistry.org/dataset/shc-activities | shc-activities
2.02 | None | https://iatiregistry.org/dataset/shc-org | shc-org
2.02 | None | https://iatiregistry.org/dataset/sjg-activities | sjg-activities
2.02 | None | https://iatiregistry.org/dataset/ss-org-activities | ss-org-activities
2.02 | None | https://iatiregistry.org/dataset/st_vluchteling-activities | st_vluchteling-activities
2.02 | None | https://iatiregistry.org/dataset/stad-activities | stad-activities
2.02 | None | https://iatiregistry.org/dataset/tbalert-activities | tbalert-activities
2.02 | None | https://iatiregistry.org/dataset/tbi-activities | tbi-activities
2.02 | None | https://iatiregistry.org/dataset/tearfund-activities | tearfund-activities
2.02 | None | https://iatiregistry.org/dataset/the_power_of_nutrition-activities | the_power_of_nutrition-activities
2.02 | None | https://iatiregistry.org/dataset/tni-activities | tni-activities
2.02 | None | https://iatiregistry.org/dataset/tns-298 | tns-298
2.02 | None | https://iatiregistry.org/dataset/tns-org | tns-org
2.02 | None | https://iatiregistry.org/dataset/uawc-ps | uawc-ps
2.02 | None | https://iatiregistry.org/dataset/uhai-eashri-activities | uhai-eashri-activities
2.02 | None | https://iatiregistry.org/dataset/unaids-uz | unaids-uz
2.02 | None | https://iatiregistry.org/dataset/uq-activities | uq-activities
2.02 | None | https://iatiregistry.org/dataset/utd-998 | utd-998
2.02 | None | https://iatiregistry.org/dataset/vei_nl-activities | vei_nl-activities
2.02 | None | https://iatiregistry.org/dataset/warchildholland-activities | warchildholland-activities
2.02 | None | https://iatiregistry.org/dataset/warchildholland-org | warchildholland-org
2.02 | None | https://iatiregistry.org/dataset/wcuk-activities | wcuk-activities
2.02 | None | https://iatiregistry.org/dataset/wedo-activities | wedo-activities
2.02 | None | https://iatiregistry.org/dataset/welbodipartnership-activities | welbodipartnership-activities
2.02 | None | https://iatiregistry.org/dataset/wfm-igp-activities | wfm-igp-activities
2.02 | None | https://iatiregistry.org/dataset/wri-activities | wri-activities
2.02 | None | https://iatiregistry.org/dataset/wri-org | wri-org
2.02 | None | https://iatiregistry.org/dataset/wusc-activities | wusc-activities
2.02 | None | https://iatiregistry.org/dataset/wvnld-activities | wvnld-activities
2.02 | None | https://iatiregistry.org/dataset/wvsyria-sy | wvsyria-sy
2.02 | None | https://iatiregistry.org/dataset/wvuk-sy | wvuk-sy
2.02 | None | https://iatiregistry.org/dataset/wygi-activities | wygi-activities
2.02 | None | https://iatiregistry.org/dataset/zoa-activities | zoa-activities

**Comment by derwas** [comment]
This issue related to IATI archiver that I have recently fixed.

The issue is fixed now!

**Comment by andylolz** [comment]
The following still appear to have issues:

actual version (in data) | registry version (in metadata) | dataset URL | dataset name
----------------|------------------|-------------|-------------
2.01 |  | https://iatiregistry.org/dataset/gac-amc-act_2_3 | gac-amc-act_2_3
2.02 | - | https://iatiregistry.org/dataset/dca-lb | dca-lb
2.02 | - | https://iatiregistry.org/dataset/dca-ml | dca-ml
2.02 | - | https://iatiregistry.org/dataset/edt_kenya-ke | edt_kenya-ke
2.01 | - | https://iatiregistry.org/dataset/said-org | said-org
2.02 | - | https://iatiregistry.org/dataset/utd-998 | utd-998
2.02 | - | https://iatiregistry.org/dataset/vei_nl-activities | vei_nl-activities
2.02 | - | https://iatiregistry.org/dataset/wygi-activities | wygi-activities
2.02 | - | https://iatiregistry.org/dataset/warchildholland-activities | warchildholland-activities
2.02 | - | https://iatiregistry.org/dataset/warchildholland-org | warchildholland-org
2.02 | - | https://iatiregistry.org/dataset/wcuk-activities | wcuk-activities
2.02 | - | https://iatiregistry.org/dataset/welbodipartnership-activities | welbodipartnership-activities
2.01 | - | https://iatiregistry.org/dataset/wfwiuk-activities | wfwiuk-activities
2.02 | - | https://iatiregistry.org/dataset/wedo-activities | wedo-activities
2.02 | - | https://iatiregistry.org/dataset/wfm-igp-activities | wfm-igp-activities
2.02 | - | https://iatiregistry.org/dataset/wri-activities | wri-activities
2.02 | - | https://iatiregistry.org/dataset/wri-org | wri-org
2.02 | - | https://iatiregistry.org/dataset/wusc-activities | wusc-activities
2.02 | - | https://iatiregistry.org/dataset/wvnld-activities | wvnld-activities
2.02 | - | https://iatiregistry.org/dataset/wvsyria-sy | wvsyria-sy
2.02 | - | https://iatiregistry.org/dataset/wvuk-sy | wvuk-sy
2.02 | - | https://iatiregistry.org/dataset/zoa-activities | zoa-activities

**Comment by derwas** [comment]
@andylolz is this list still the same?

**Comment by andylolz** [comment]
@derwas most of the list looks sorted!

https://iatiregistry.org/dataset/gac-amc-act_2_3 still shows up as blank, but that might be a result of the error shown.

https://iatiregistry.org/dataset/said-org is still wrong, but IIRC that’s due to the dataset not following the naming convention (the publisher is called `said-uk` so the dataset should be `said-uk-org`). There’s some discussion about that here: https://github.com/IATI/ckanext-iati/issues/117#issuecomment-340473322.

Apart from that, the list above looks good now :)

**Comment by andylolz** [comment]
> wondered if there was any update on the two remaining issues highlighted immediately above

They’re both still wrong, but I suspect in both cases it’s for unrelated reasons. So I think this can be closed.

**Comment by amy-silcock** [comment]
All above issues now look fixed. Lets close this. Further fixes have been implemented with the recent archiver work.
