### ISSUE TITLE
Sync drop down list of countries with IATI codelist

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#200]
Hi,

Please can we sync the drop down list of countries, used when orgs sign to up, with the IATI country codelist: http://reference.iatistandard.org/203/codelists/Country/ ?

It looks like this process may currently be manual? https://github.com/derilinx/ckanext-iati/blob/master/ckanext/iati/countries.xml

Thank you,

Amy

**Comment by amy-silcock** [comment]
I've tried to update the codelist but may have done it in the wrong place? https://github.com/IATI/ckanext-iati/pull/202

**Comment by derwas** [comment]
Fixed in this [commit](https://github.com/IATI/ckanext-iati/commit/ed6a204e18fe5ffd7b8ca021503539b170bc8e49)!

**Comment by amy-silcock** [comment]
Hi Wassim, 

I can see that the list is now up to date.

Can we please also get the changes on the list of publishers? Such as the Czech Republic is still showing, rather than Czechia:

![image](https://user-images.githubusercontent.com/27764077/45291926-6c2cf500-b4eb-11e8-83a2-eb9f23fca5dc.png)

**Comment by amy-silcock** [comment]
@amy-silcock to send list of changed names across

**Comment by derwas** [comment]
@amy-silcock I have just sent you an email about the changes required.

Check this file https://github.com/IATI/ckanext-iati/blob/ckan-2.8.1/ckanext/iati/countries.py

**Comment by derwas** [comment]
Updated on the server!

**Comment by amy-silcock** [comment]
Great, just checked and it's all there :)
