### ISSUE TITLE
Publisher ID for `dmru` has changed, but its dataset IDs have not

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#316]
It looks as though the publisher ID for [Center for Church-Based Development](https://iatiregistry.org/publisher/cku) has been changed? I think it was previously `dmru`, but is now `cku`.

Redirects have been set up for the datasets (e.g. https://iatiregistry.org/dataset/dmru-998 redirects to https://iatiregistry.org/dataset/cku-998). However, the dataset IDs haven’t been changed, so these redirects 404.

I _think_ it’s a rule that dataset IDs are always prefixed by their publisher ID, which is currently not the case here. The redirects are useful, but it’s more important that the publisher ID and dataset IDs match up.

**Comment by andylolz** [comment]
> I think it’s a rule that dataset IDs are always prefixed by their publisher ID

I think this constraint is enforced when dataset metadata is modified:
![Screenshot 2021-01-29 at 13 32 54](https://user-images.githubusercontent.com/464193/106302447-e7c0a580-6250-11eb-95d5-9e1291af6810.png)

I think the problem here is that dataset IDs aren’t auto-updated when a publisher ID is changed.

**Comment by andreaszenasidi** [comment]
@andylolz thanks for spotting this issue. It was prioritized for Q1.

**Comment by andylolz** [comment]
That’s great.

In the short term, I assume an admin can log in and rename the 7 datasets? I.e. changing the `dmru-` prefix to `cku-`.

The longer term fix would involve making this dataset renaming automatic when the publisher is renamed.

**Comment by gtkChop** [comment]
@andylolz @andreaszenasidi 

Short term fix:

Disabled the redirect for now. All datasets should be accessible. (redirects don't work for now)

This problem was due to the CKAN upgrade. We had a redirect is ckan 2.9.8 which was pylons but the new version runs on the flask, hence it behaves differently.

Long term solution:

* We will be adding redirect in Nginx rather than CKAN.
* As @andy mentioned On change of publisher id we need to add validator that changes the name of the datasets to <pub_id>-<name>

**Comment by andylolz** [comment]
Great, thanks. That’s an improvement (the datasets are now accessible). However, the dataset IDs still don’t match up with the publisher ID. To resolve that, I think this bit still needs to happen:

> I assume an admin can log in and rename the 7 datasets? I.e. changing the dmru- prefix to cku-.

**Comment by gtkChop** [comment]
@andy

Yes, needs some dev work to make that happen and would take some time.

However, just to make things clear, after implementing the functionality

* Old dataset scenario remains the same with old datasets (unless we write a script to changes all the existing datasets names whose publisher id changed)
* From now on any change in publisher id, dataset name should also be changed accordingly.

**Comment by andylolz** [comment]
> unless we write a script to changes all the existing datasets names whose publisher id changed

I think it’s just 7 datasets. An admin ought to be able to do this manually, without the need for a script.
 * [Danish Mission Council Development Organisation Organisation File
](https://iatiregistry.org/dataset/dmru-org)
 * [Danish Mission Council Development Organisation Activity File-DK](https://iatiregistry.org/dataset/dmru-dk)
 * [Danish Mission Council Development Organisation Activity File-CN](https://iatiregistry.org/dataset/dmru-cn)
 * [Danish Mission Council Development Organisation Activity File-BE](https://iatiregistry.org/dataset/dmru-be)
 * [Danish Mission Council Development Organisation Activity File-998](https://iatiregistry.org/dataset/dmru-998)
 * [Activities of the DMCDD funds](https://iatiregistry.org/dataset/dmru-999)
 * [Activities of the CKU funds (including FoRB and RfD)](https://iatiregistry.org/dataset/dmru-all)

I think these 7 datasets should be renamed, so that the prefix is changed from `dmru` to `cku`.

It’s likely this issue will break some IATI tools, since it violates the rule that dataset IDs are prefixed by their publisher ID. I only came across this issue because it caused an IATI tool I contribute to to break.

**Comment by gtkChop** [comment]
@andreaszenasidi @andylolz 

This is fixed. However, the below dataset names should be changed manually

 * [Danish Mission Council Development Organisation Organisation File
](https://iatiregistry.org/dataset/dmru-org)
 * [Danish Mission Council Development Organisation Activity File-DK](https://iatiregistry.org/dataset/dmru-dk)
 * [Danish Mission Council Development Organisation Activity File-CN](https://iatiregistry.org/dataset/dmru-cn)
 * [Danish Mission Council Development Organisation Activity File-BE](https://iatiregistry.org/dataset/dmru-be)
 * [Danish Mission Council Development Organisation Activity File-998](https://iatiregistry.org/dataset/dmru-998)
 * [Activities of the DMCDD funds](https://iatiregistry.org/dataset/dmru-999)
 * [Activities of the CKU funds (including FoRB and RfD)](https://iatiregistry.org/dataset/dmru-all)
 
 
 Please let me know if you encounter any issues. Thanks

**Comment by andylolz** [comment]
> This is fixed.

The issue title here is: **“Publisher ID for `dmru` has changed, but its dataset IDs have not”**. That problem still applies. So I don’t think this can be considered fixed yet.

> However, the below dataset names should be changed manually

What needs to happen to make this change happen? I guess the publisher needs to do this in Aidstream?

**Comment by gtkChop** [comment]
@andylolz Yes, you are right. The new feature is applicable to only those publishers whose names will be changed from now on. It doesn't apply to all the old publishers.

So next step would be cleaning the datasets whose names doest follow the naming convention. (Pending)

**Comment by gtkChop** [comment]
Pending taks:

- [ ] Handle a large number of datasets (The current limit is 100), run as background jobs.
- [ ] Change all dataset names (old) whose names don't follow the convention.

**Comment by andreaszenasidi** [comment]
@gtkChop I tested this on staging. When I change the publisher id the dataset 'field id' gets updated but only for Public datasets. Private dataset id's should be also updated since publishers could make these public again.

**Comment by gtkChop** [comment]
@andreaszenasidi This is fixed in staging. Could you please test in staging?

If good I will deploy to production. 

Please Note:

Change in publisher name may not be reflected immediately in the dataset because the process is run as a background job and would take some time to reflect.

**Comment by andreaszenasidi** [comment]
@gtkChop I found two issues during testing:
1. When **Update Publisher** button is clicked on the publisher [edit page](https://staging.iatiregistry.org/publisher/edit/app1upd) the page stays on the old publisher page with the old publisher id in the link which leads to a 404 error. The publisher is renamed though as expected.
I changed the publisher id from **app1up** to **app1upd**, see 404 error received below:

![image](https://user-images.githubusercontent.com/74558657/117122185-851a0100-ad8d-11eb-8caa-8ce0d644eaa3.png)

**Expected behaviour:** When a publisher id is updated after saving the new settings the user should be redirected to the new publisher page, in the above example https://staging.iatiregistry.org/publisher/edit/app1upd 

2. The private dataset IDs are not changed to the new publisher id. See dataset: https://staging.iatiregistry.org/dataset/ap-222 Where **ap** is an old publisher id. It should be **app1upd**. This also causes the links in the breadcrumbs menu to be broken; in the screenshot below the **Andi Publisher** takes you to https://staging.iatiregistry.org/publisher/ap which doesn't exist.

![image](https://user-images.githubusercontent.com/74558657/117122857-3882f580-ad8e-11eb-9deb-ecc47c415461.png)

**Expected behaviour:** Private dataset IDs should be renamed. In the above example, https://staging.iatiregistry.org/dataset/ap-222 should be https://staging.iatiregistry.org/dataset/app1upd-222

**Publisher used for testing:** ["Andi Publisher" ](https://staging.iatiregistry.org/publisher/app1upd) - 55 public and 1 private datasets

**Comment by gtkChop** [comment]
@andreaszenasidi 

This is fixed. Please note - after a change in publisher name - please wait for sometime and reload the page to reflect the changes. Thanks

https://staging.iatiregistry.org/publisher/app222

**Comment by andreaszenasidi** [comment]
@gtkChop Tested and it works well now. 

Tested with https://staging.iatiregistry.org/publisher/pidtest that had 34 public activity files, 2 public org files, 2 private org files and 2 private activity files. Publisher id and dataset names were all updated successfully
https://staging.iatiregistry.org/publisher/pidtest12 

The only remaining item is to manually update [these ](https://github.com/IATI/ckanext-iati/issues/316#issuecomment-810993794) datasets?

**Comment by gtkChop** [comment]
@andreaszenasidi 

Deployed

**Comment by andreaszenasidi** [comment]
@andylolz Center for Church-Based Development's dataset names are now all correct.

**Comment by andylolz** [comment]
Great – thank you both!
