### ISSUE TITLE
Recent publishers list not up to date

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#321]
The recent publishers list is not up to date, and there's a random inclusion of the Welsh Government who are currently publishing no data: https://www.iatiregistry.org/dashboard/recent-publishers

For example, the university of Sheffield published on the 01/02/2021 and are not on the list.

![image](https://user-images.githubusercontent.com/27764077/106734667-2f597f80-660b-11eb-886b-1f687b6581de.png)

**Comment by gtkChop** [comment]
Thanks, @amy for spotting this.

Yes, the first published data is not updated in the DB, hence it's not visible on the recent publisher's page.

I spotted a bug around this and working on this. I will update you soon.

**Comment by amy-silcock** [comment]
Great, thank you!

**Comment by gtkChop** [comment]
@amy-silcock 

There was a bug in IATI First publisher date. 

When a new dataset is created for a new publisher first publisher date was not capturing. This is fixed now.

Steps:

* You can manually update the publisher OR
* If you update the publisher (the first publisher date should be updated).

Once the date is updated, I will appear in Recent publisher page.

**Comment by andreaszenasidi** [comment]
@gtkChop I think there is still an issue with the First Published Date, [this](https://iatiregistry.org/publisher/ces-ua) org published today Feb 4th, 2021 and the date is still empty.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Updated the first publisher date logic and tested it with the following scenarios.

- Creating a new public dataset
- Creating a new private dataset and then making the dataset public.
- Organization should be visible on the recent publisher's page (sysadmin only).


Please let me know if you encounter issues again. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop Was this fix deployed?

**Comment by andreaszenasidi** [comment]
@gtkChop tested in staging and looks good.

**Comment by andreaszenasidi** [comment]
The list is up to date. Closing.
